import type { Topic } from './types';

export const topics: Topic[] = [
  // The 12 Steps
  { id: 'step-1', category: 'Step', title: 'Step 1: Powerlessness', description: 'We admitted we were powerless over alcohol—that our lives had become unmanageable.' },
  { id: 'step-2', category: 'Step', title: 'Step 2: Hope', description: 'Came to believe that a Power greater than ourselves could restore us to sanity.' },
  { id: 'step-3', category: 'Step', title: 'Step 3: Surrender', description: 'Made a decision to turn our will and our lives over to the care of God as we understood Him.' },
  { id: 'step-4', category: 'Step', title: 'Step 4: Inventory', description: 'Made a searching and fearless moral inventory of ourselves.' },
  { id: 'step-5', category: 'Step', title: 'Step 5: Admission', description: 'Admitted to God, to ourselves, and to another human being the exact nature of our wrongs.' },
  { id: 'step-6', category: 'Step', title: 'Step 6: Readiness', description: 'Were entirely ready to have God remove all these defects of character.' },
  { id: 'step-7', category: 'Step', title: 'Step 7: Humility', description: 'Humbly asked Him to remove our shortcomings.' },
  { id: 'step-8', category: 'Step', title: 'Step 8: Willingness', description: 'Made a list of all persons we had harmed, and became willing to make amends to them all.' },
  { id: 'step-9', category: 'Step', title: 'Step 9: Amends', description: 'Made direct amends to such people wherever possible, except when to do so would injure them or others.' },
  { id: 'step-10', category: 'Step', title: 'Step 10: Maintenance', description: 'Continued to take personal inventory and when we were wrong promptly admitted it.' },
  { id: 'step-11', category: 'Step', title: 'Step 11: Prayer & Meditation', description: 'Sought through prayer and meditation to improve our conscious contact with God as we understood Him, praying only for knowledge of His will for us and the power to carry that out.' },
  { id: 'step-12', category: 'Step', title: 'Step 12: Service', description: 'Having had a spiritual awakening as the result of these steps, we tried to carry this message to alcoholics, and to practice these principles in all our affairs.' },

  // The 12 Traditions
  { id: 'trad-1', category: 'Tradition', title: 'Tradition 1: Unity', description: 'Our common welfare should come first; personal recovery depends upon A.A. unity.' },
  { id: 'trad-2', category: 'Tradition', title: 'Tradition 2: Leadership', description: 'For our group purpose there is but one ultimate authority—a loving God as He may express Himself in our group conscience. Our leaders are but trusted servants; they do not govern.' },
  { id: 'trad-3', category: 'Tradition', title: 'Tradition 3: Eligibility', description: 'The only requirement for A.A. membership is a desire to stop drinking.' },
  { id: 'trad-4', category: 'Tradition', title: 'Tradition 4: Autonomy', description: 'Each group should be autonomous except in matters affecting other groups or A.A. as a whole.' },
  { id: 'trad-5', category: 'Tradition', title: 'Tradition 5: Primary Purpose', description: 'Each group has but one primary purpose—to carry its message to the alcoholic who still suffers.' },
  { id: 'trad-6', category: 'Tradition', title: 'Tradition 6: Non-Affiliation', description: 'An A.A. group ought never endorse, finance, or lend the A.A. name to any related facility or outside enterprise, lest problems of money, property, and prestige divert us from our primary purpose.' },
  { id: 'trad-7', category: 'Tradition', title: 'Tradition 7: Self-Support', description: 'Every A.A. group ought to be fully self-supporting, declining outside contributions.' },
  { id: 'trad-8', category: 'Tradition', title: 'Tradition 8: Non-Professionalism', description: 'Alcoholics Anonymous should remain forever non-professional, but our service centers may employ special workers.' },
  { id: 'trad-9', category: 'Tradition', title: 'Tradition 9: Organization', description: 'A.A., as such, ought never be organized; but we may create service boards or committees directly responsible to those they serve.' },
  { id: 'trad-10', category: 'Tradition', title: 'Tradition 10: Outside Issues', description: 'Alcoholics Anonymous has no opinion on outside issues; hence the A.A. name ought never be drawn into public controversy.' },
  { id: 'trad-11', category: 'Tradition', title: 'Tradition 11: Anonymity (Public)', description: 'Our public relations policy is based on attraction rather than promotion; we need always maintain personal anonymity at the level of press, radio, and films.' },
  { id: 'trad-12', category: 'Tradition', title: 'Tradition 12: Anonymity (Spiritual)', description: 'Anonymity is the spiritual foundation of all our Traditions, ever reminding us to place principles before personalities.' },

  // The Promises
  { id: 'promise-1', category: 'Promise', title: 'The Promises', description: 'If we are painstaking about this phase of our development, we will be amazed before we are half way through.' },
  { id: 'promise-2', category: 'Promise', title: 'Promise: Freedom', description: 'We are going to know a new freedom and a new happiness.' },
  { id: 'promise-3', category: 'Promise', title: 'Promise: Past', description: 'We will not regret the past nor wish to shut the door on it.' },
  { id: 'promise-4', category: 'Promise', title: 'Promise: Perspective', description: 'We will comprehend the word serenity and we will know peace.' },
  { id: 'promise-5', category: 'Promise', title: 'Promise: Experience', description: 'No matter how far down the scale we have gone, we will see how our experience can benefit others.' },
  { id: 'promise-6', category: 'Promise', title: 'Promise: Feeling', description: 'That feeling of uselessness and self-pity will disappear.' },
  { id: 'promise-7', category: 'Promise', title: 'Promise: Interest', description: 'We will lose interest in selfish things and gain interest in our fellows.' },
  { id: 'promise-8', category: 'Promise', title: 'Promise: Self-Seeking', description: 'Self-seeking will slip away.' },
  { id: 'promise-9', category: 'Promise', title: 'Promise: Intuition', description: 'Our whole attitude and outlook upon life will change.' },
  { id: 'promise-10', category: 'Promise', title: 'Promise: Fear', description: 'Fear of people and of economic insecurity will leave us.' },
  { id: 'promise-11', category: 'Promise', title: 'Promise: Intuitive Guidance', description: 'We will intuitively know how to handle situations which used to baffle us.' },
  { id: 'promise-12', category: 'Promise', title: 'Promise: Realization', description: 'We will suddenly realize that God is doing for us what we could not do for ourselves.' },

  // Big Book Themes
  { id: 'bb-doctor', category: 'Big Book', title: "The Doctor's Opinion", description: 'Dr. Silkworth\'s foundational medical perspective on alcoholism as an illness.' },
  { id: 'bb-bill', category: 'Big Book', title: "Bill's Story", description: 'The story of AA co-founder Bill Wilson and his journey to recovery.' },
  { id: 'bb-agitators', category: 'Big Book', title: 'There Is a Solution', description: 'The problem of alcoholism and the hope found in the AA program.' },
  { id: 'bb-more', category: 'Big Book', title: 'More About Alcoholism', description: 'Understanding the nature of alcoholism and the mental obsession.' },
  { id: 'bb-agnostic', category: 'Big Book', title: 'We Agnostics', description: 'Addressing spiritual concerns and finding a Higher Power that works for you.' },
  { id: 'bb-how', category: 'Big Book', title: 'How It Works', description: 'The detailed explanation of the Twelve Steps and their application.' },
  { id: 'bb-vision', category: 'Big Book', title: 'Into Action', description: 'Putting the Steps into practice in daily life.' },
  { id: 'bb-working', category: 'Big Book', title: 'Working With Others', description: 'How to carry the message to those who still suffer.' },
  { id: 'bb-family', category: 'Big Book', title: 'To Wives / The Family', description: 'The impact of alcoholism on family and relationships.' },
  { id: 'bb-employer', category: 'Big Book', title: 'To Employers', description: 'Understanding and helping the alcoholic employee.' },
  { id: 'bb-vary', category: 'Big Book', title: 'A Vision For You', description: 'The promise of recovery and the fellowship that awaits.' },

  // Common Discussion Topics
  { id: 'topic-gratitude', category: 'Discussion', title: 'Gratitude', description: 'Cultivating an attitude of thankfulness in recovery.' },
  { id: 'topic-acceptance', category: 'Discussion', title: 'Acceptance', description: 'Learning to accept life on life\'s terms.' },
  { id: 'topic-surrender', category: 'Discussion', title: 'Surrender', description: 'Letting go of control and trusting the process.' },
  { id: 'topic-honesty', category: 'Discussion', title: 'Honesty', description: 'The foundation of recovery—rigorous honesty with self and others.' },
  { id: 'topic-openminded', category: 'Discussion', title: 'Open-Mindedness', description: 'Willingness to consider new ideas and approaches.' },
  { id: 'topic-willingness', category: 'Discussion', title: 'Willingness', description: 'The key that unlocks the door to recovery.' },
  { id: 'topic-faith', category: 'Discussion', title: 'Faith', description: 'Trusting in a Power greater than ourselves.' },
  { id: 'topic-courage', category: 'Discussion', title: 'Courage', description: 'Facing our fears and taking action despite them.' },
  { id: 'topic-integrity', category: 'Discussion', title: 'Integrity', description: 'Living in alignment with our values.' },
  { id: 'topic-humility', category: 'Discussion', title: 'Humility', description: 'Keeping our egos in check and staying teachable.' },
  { id: 'topic-patience', category: 'Discussion', title: 'Patience', description: 'Trusting in the timing of our recovery.' },
  { id: 'topic-tolerance', category: 'Discussion', title: 'Tolerance', description: 'Accepting differences and practicing love for all.' },
  { id: 'topic-love', category: 'Discussion', title: 'Love', description: 'Learning to love ourselves and others unconditionally.' },
  { id: 'topic-service', category: 'Discussion', title: 'Service', description: 'Finding purpose through helping others.' },
  { id: 'topic-fellowship', category: 'Discussion', title: 'Fellowship', description: 'The power of connection and community in recovery.' },
  { id: 'topic-spirituality', category: 'Discussion', title: 'Spirituality', description: 'Developing a spiritual life in recovery.' },
  { id: 'topic-prayer', category: 'Discussion', title: 'Prayer', description: 'Communicating with our Higher Power.' },
  { id: 'topic-meditation', category: 'Discussion', title: 'Meditation', description: 'Listening to our Higher Power through quiet reflection.' },
  { id: 'topic-forgiveness', category: 'Discussion', title: 'Forgiveness', description: 'Letting go of resentments toward self and others.' },
  { id: 'topic-amends', category: 'Discussion', title: 'Making Amends', description: 'The healing power of repairing our past.' },
  { id: 'topic-sponsor', category: 'Discussion', title: 'Sponsorship', description: 'The vital relationship between sponsor and sponsee.' },
  { id: 'topic-homegroup', category: 'Discussion', title: 'Home Group', description: 'Finding our place in the AA fellowship.' },
  { id: 'topic-meetings', category: 'Discussion', title: 'Meetings', description: 'The importance of regular meeting attendance.' },
  { id: 'topic-tools', category: 'Discussion', title: 'Recovery Tools', description: 'The many tools we use to stay sober.' },
  { id: 'topic-triggers', category: 'Discussion', title: 'Triggers', description: 'Identifying and managing people, places, and things.' },
  { id: 'topic-cravings', category: 'Discussion', title: 'Cravings & Urges', description: 'Dealing with the desire to drink.' },
  { id: 'topic-relapse', category: 'Discussion', title: 'Relapse Prevention', description: 'Staying vigilant and protecting our recovery.' },
  { id: 'topic-progress', category: 'Discussion', title: 'Progress Not Perfection', description: 'Embracing growth without demanding perfection.' },
  { id: 'topic-one-day', category: 'Discussion', title: 'One Day at a Time', description: 'Living in the present moment.' },
  { id: 'topic-first-things', category: 'Discussion', title: 'First Things First', description: 'Prioritizing our recovery above all else.' },
  { id: 'topic-live-let-live', category: 'Discussion', title: 'Live and Let Live', description: 'Finding peace by letting go of control over others.' },
  { id: 'topic-easy-does', category: 'Discussion', title: 'Easy Does It', description: 'Taking a gentle approach to life and recovery.' },
  { id: 'topic-think', category: 'Discussion', title: 'Think, Think, Think', description: 'Using our minds to support rather than sabotage recovery.' },
  { id: 'topic-keep-it', category: 'Discussion', title: 'Keep It Simple', description: 'Avoiding unnecessary complexity in our program.' },
  { id: 'topic-but-for', category: 'Discussion', title: 'But for the Grace of God', description: 'Recognizing the gift of sobriety.' },
  { id: 'topic-gift', category: 'Discussion', title: 'The Gift of Sobriety', description: 'Appreciating what we have been given.' },

  // Daily Reflection Themes
  { id: 'dr-jan', category: 'Daily Reflection', title: 'January: Surrender', description: 'Surrendering our will and accepting help.' },
  { id: 'dr-feb', category: 'Daily Reflection', title: 'February: Peace & Serenity', description: 'Finding inner calm through the program.' },
  { id: 'dr-mar', category: 'Daily Reflection', title: 'March: Powerlessness', description: 'Accepting our limitations and need for help.' },
  { id: 'dr-apr', category: 'Daily Reflection', title: 'April: Trust', description: 'Learning to trust the process and our Higher Power.' },
  { id: 'dr-may', category: 'Daily Reflection', title: 'May: Action', description: 'Taking positive steps in our recovery.' },
  { id: 'dr-jun', category: 'Daily Reflection', title: 'June: Willingness', description: 'Being open to change and growth.' },
  { id: 'dr-jul', category: 'Daily Reflection', title: 'July: Spirituality', description: 'Deepening our spiritual connection.' },
  { id: 'dr-aug', category: 'Daily Reflection', title: 'August: Perspective', description: 'Seeing our lives through the lens of recovery.' },
  { id: 'dr-sep', category: 'Daily Reflection', title: 'September: Humility', description: 'Staying right-sized and teachable.' },
  { id: 'dr-oct', category: 'Daily Reflection', title: 'October: Faith', description: 'Strengthening our belief in the program.' },
  { id: 'dr-nov', category: 'Daily Reflection', title: 'November: Gratitude', description: 'Counting our blessings.' },
  { id: 'dr-dec', category: 'Daily Reflection', title: 'December: Service', description: 'Giving back what was freely given to us.' },

  // Additional Program Topics
  { id: 'prog-90', category: 'Program', title: '90 in 90', description: 'The benefit of attending 90 meetings in 90 days.' },
  { id: 'prog-book', category: 'Program', title: 'Big Book Study', description: 'Studying the basic text of Alcoholics Anonymous.' },
  { id: 'prog-step', category: 'Program', title: 'Step Study', description: 'Working the Steps with a sponsor.' },
  { id: 'prog-sponsor', category: 'Program', title: 'Getting a Sponsor', description: 'Finding and working with a sponsor.' },
  { id: 'prog-sponsee', category: 'Program', title: 'Being a Sponsor', description: 'Carrying the message through sponsorship.' },
  { id: 'prog-commitment', category: 'Program', title: 'Service Commitments', description: 'Giving back through service work.' },
  { id: 'prog-conference', category: 'Program', title: 'Conference-Approved Literature', description: 'The importance of using official AA literature.' },
  { id: 'prog-anonymity', category: 'Program', title: 'Anonymity', description: 'The spiritual foundation of our program.' },
  { id: 'prog-tradition', category: 'Program', title: 'Living the Traditions', description: 'Applying the Traditions in our daily lives.' },
  { id: 'prog-concept', category: 'Program', title: 'The Twelve Concepts', description: 'World service principles for AA as a whole.' },
  { id: 'prog-joy', category: 'Program', title: 'Happy, Joyous, and Free', description: 'The promises of recovery fulfilled.' },
  { id: 'prog-design', category: 'Program', title: 'A New Design for Living', description: 'Creating a life worth living in sobriety.' },
];
